/*
-- Query: SELECT * FROM edu_ecommerce_kel1.customers
LIMIT 0, 1000

-- Date: 2023-06-20 14:21
*/
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (1,'Ahmad Maulana','ahmadmaulana@example.com','Banda Aceh');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (2,'Siti Rahayu','sitirahayu@example.com','Denpasar');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (3,'Budi Santoso','budisantoso@example.com','Palu');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (4,'Dewi Lestari','dewilestari@example.com','Pekanbaru');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (5,'Hadi Prasetyo','hadiprasetyo@example.com','Banjarmasin');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (6,'Rina Fitriani','rinafitriani@example.com','Malang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (7,'Agus Setiawan','agussetiawan@example.com','Bandar Lampung');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (8,'Rita Puspitasari','ritapuspitasari@example.com',' Manado');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (9,'Hendra Kurniawan','hendrakurniawan@example.com','Mataram');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (10,'Maya Sari','mayasari@example.com','Pontianak');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (11,'Eko Santoso','ekosantoso@example.com','Batam');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (12,'Anita Wulandari','anitawulandari@example.com','Jayapura');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (13,'Rudi Hartono','rudihartono@example.com','Makassar');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (14,'Nita Permata','nitapermata@example.com','Semarang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (15,'Dian Nugraha','dianugraha@example.com','Surakarta');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (16,'Siti Mulyani','sitimulyani@example.com','Surabaya');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (17,'Fauzi Rahman','fauzirahman@example.com','Samarinda');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (18,'Sari Indah','sariindah@example.com','Medan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (19,'Dedi Pratama','dedipratama@example.com','Balikpapan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (20,'Anita Dewi','anitadewi@example.com','Padang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (21,'Rudi Susanto','rudisusanto@example.com','Palembang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (22,'Yulia Purnama','yuliapurnama@example.com','Bandung');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (23,'Agus Setiadi','agussetiadi@example.com','Jakarta');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (24,'Fitriani Dewi','fitrianidewi@example.com','Yogyakarta');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (25,'Hendra Gunawan','hendragunawan@example.com','Kendari');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (26,'Dewi Kusuma','dewikusuma@example.com','Jambi');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (27,'Irfan Prasetyo','irfanprasetyo@example.com','Ternate');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (28,'Siti Fatimah','sitifatimah@example.com','Kupang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (29,'Rina Susanti','rianasusanti@example.com','Ambon');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (30,'Adi Nugroho','adinugroho@example.com','Gorontalo');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (31,'Lia Pratiwi','liapratiwi@example.com','Tomohon');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (32,'Budi Hartanto','budihartanto@example.com','Singkawang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (33,'Rita Indah','ritaindah@example.com','Palangkaraya');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (34,'Diana Maulida','dianamaulida@example.com','Tarakan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (35,'Sandy Kurniawan','sandykurniawan@example.com','Bengkulu');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (36,'Maya Surya','mayasurya@example.com','Bukittinggi');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (37,'Eko Prasetya','ekoprasetya@example.com','Cirebon');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (38,'Ratna Puspita','ratnapuspita@example.com','Pangkal Pinang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (39,'Ahmad Santoso','ahmadsantoso@example.com','Bandar Aceh');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (40,'Lina Fitriani','linafitriani@example.com','Tangerang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (41,'Fajar Setiawan','fajarsitiawan@example.com','Serang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (42,'Nita Dewi','nitadewi@example.com',' Cianjur');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (43,'Rudi Prasetyo','rudiprasetyo@example.com','Malang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (44,'Siti Rahma','sitirahma@example.com','Jember');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (45,'Dedy Wijaya','dedywijaya@example.com','Mojokerto');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (46,'Nina Purnama','ninapurnama@example.com','Sidoarjo');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (47,'Eko Setiadi','ekosetiadi@example.com','Batu');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (48,'Anita Sari','anitasari@example.com','Bontang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (49,'Rudi Gunawan','rudigunawan@example.com','Singaraja');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (50,'Yulia Kusuma','yuliakusuma@example.com','Sukabumi');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (51,'Agus Hartono','agushartono@example.com','Karawang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (52,'Fitriani Setiawati','fitrianisetiawati@example.com',' Magelang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (53,'Hendra Pratama','hendrapratama@example.com','Klaten');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (54,'Dewi Santoso','dewisantoso@example.com','Kediri');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (55,'Irfan Nugraha','irfannugraha@example.com','Pasuruan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (56,'Siti Mawar','sitimawar@example.com','Probolinggo');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (57,'Rina Fitriani','rinafitriani2@example.com','Banyuwangi');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (58,'Adi Santoso','adisantoso@example.com','Pekalongan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (59,'Lia Prasetyo','liaprasetyo@example.com','Tegal');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (60,'Budi Kusuma','budikusuma@example.com','Kudus');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (61,'Rita Indah','ritaindah2@example.com','Bojonegoro');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (62,'Diana Maulana','dianamaulana@example.com','Tuban');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (63,'Sandy Kurniati','sandykurniati@example.com','Blitar');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (64,'Maya Suryanto','mayasuryanto@example.com','Madiun');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (65,'Eko Prasetyo2','ekoprasetyo2@example.com','Nganjuk');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (66,'Ratna Puspitasari2','ratnapuspitasari2@example.com','Ponorogo');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (67,'Ahmad Santosa','ahmadsantosa@example.com','Tulungagung');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (68,'Lina Fitriani2','linafitriani2@example.com','Pacitan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (69,'Fajar Setiawan2','fajarsitiawan2@example.com','Sampang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (70,'Nita Dewi2','nitadewi2@example.com','Bangkalan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (71,'Rudi Prasetyo2','rudiprasetyo2@example.com','Sumenep');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (72,'Siti Rahma2','sitirahma2@example.com','Pamekasan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (73,'Dedy Wijaya2','dedywijaya2@example.com','Kupang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (74,'Nina Purnama2','ninapurnama2@example.com','Larantuka');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (75,'Eko Setiadi2','ekosetiadi2@example.com','Waingapu');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (76,'Anita Sari2','anitasari2@example.com','Ende');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (77,'Rudi Gunawan2','rudigunawan2@example.com','Maumere');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (78,'Yulia Kusuma2','yuliakusuma2@example.com','Ruteng');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (79,'Agus Hartono2','agushartono2@example.com','Bajawa');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (80,'Fitriani Setiawati2','fitrianisetiawati2@example.com','Labuan Bajo');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (81,'Hendra Pratama2','hendrapratama2@example.com','Singkawang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (82,'Dewi Santoso2','dewisantoso2@example.com','Melawi');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (83,'Irfan Nugraha2','irfannugraha2@example.com','Bengkulu');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (84,'Siti Mawar2','sitimawar2@example.com','Padang Sidempuan');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (85,'Aubrey Bryant','aubreybryant@example.com','Padang Panjang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (86,'Aria Reed','ariareed@example.com','Lubuklinggau');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (87,'Miles Cox','milescox@example.com','Lahat');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (88,'Ellie Sanders','elliesanders@example.com','Prabumulih');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (89,'Caleb Wood','calebwood@example.com','Pagar Alam');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (90,'Victoria Nelson','victorianelson@example.com','Sungai Penuh');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (91,'Jack Roberts','jackroberts@example.com','Payakumbuh');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (92,'Sofia Phillips','sofiaphillips@example.com','Sawahlunto');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (93,'Gavin Bell','gavinbell@example.com','Solok');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (94,'Avery Parker','averyparker@example.com','Padang Aro');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (95,'Eleanor Phillips','eleanorphillips@example.com','Bukittinggi');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (96,'Julian Wright','julianwright@example.com',' Palembang');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (97,'Lucy Mitchell','lucymitchell@example.com','Lubuk Basung');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (98,'Lincoln Watson','lincolnwatson@example.com',' Muara Bungo');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (99,'Aurora Foster','aurorafoster@example.com','Bangko');
INSERT INTO `` (`customer_id`,`customer_name`,`email`,`address`) VALUES (100,'Henry Cox','hnerycox@example.com','Sarolangun');
