/*
-- Query: SELECT * FROM edu_ecommerce_kel1.product
LIMIT 0, 1000

-- Date: 2023-06-20 14:22
*/
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,'baju',' Clothing',150000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,'celana',' Clothing',200000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,'tas',' Accessories',75000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,'sepatu',' Accessories',250000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,'ikat Pinggang',' Accessories',20000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (3,'sepeda','transportasi',500000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,'kacamata',' Accessories',300000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,'botol minum',' Footwear',50000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (5,'pensil',' Stationery',3000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,'sikat gigi',' Footwear',12000,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Tablet H',' Electronics',3147045,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Jeans I',' Clothing',4992174,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Perfume J',' Beauty',924577,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Speaker K',' Electronics',5665240,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Hat L',' Accessories',362375,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Socks M',' Clothing',1366195,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Sunglasses N',' Accessories',1259218,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Skirt O',' Clothing',3699624,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Wallet P',' Accessories',5361705,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (8,' Bike Q',' Sports',993809,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Printer R',' Electronics',5495643,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Dress S',' Clothing',6616752,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Cologne T',' Beauty',4916909,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Bracelet U',' Accessories',2613059,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Shorts V',' Clothing',4876079,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Lipstick W',' Beauty',3305641,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Sneakers X',' Footwear',2276981,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Umbrella Y',' Accessories',535426,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (9,' Guitar Z',' Music',6397453,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Bathrobe A1',' Clothing',1864584,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Eyeshadow B1',' Beauty',4232985,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Sandals C1',' Footwear',2637807,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Game Console D1',' Electronics',4336738,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Shampoo E1',' Beauty',5456047,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Backpack F1',' Accessories',1343650,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Hoodie G1',' Clothing',2146157,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (10,' Coffee Mug H1',' Home',1985209,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Necklace I1',' Accessories',1571995,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (8,' Tennis Racket J1',' Sports',1732466,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (5,' Pencil Set K1',' Stationery',5371230,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (8,' Dumbbell L1',' Sports',4227192,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Handbag M1',' Accessories',3704512,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Moisturizer N1',' Beauty',4444037,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Scarf O1',' Accessories',6562389,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Tablet P1',' Electronics',3222631,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Running Shoes Q1',' Footwear',5857438,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Backpack R1',' Accessories',1935711,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' T-Shirt S1',' Clothing',5639310,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Wallet T1',' Accessories',1165639,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Earrings U1',' Accessories',5966252,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Speaker V1',' Electronics',5384915,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Shorts W1',' Clothing',3864647,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Cologne X1',' Beauty',3834853,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Sunglasses Y1',' Accessories',4768836,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Lip Balm Z1',' Beauty',3993523,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Laptop A2',' Electronics',2454598,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Dress B2',' Clothing',6749322,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Wallet C2',' Accessories',6043635,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Sneakers D2',' Footwear',5551404,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Backpack E2',' Accessories',4738867,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (8,' Bike F2',' Sports',1388540,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Watch G2',' Accessories',1364593,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Headphones H2',' Electronics',2241546,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Jeans I2',' Clothing',5966394,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Bracelet J2',' Accessories',2146178,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Skirt K2',' Clothing',3570322,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Cologne L2',' Beauty',85125,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Sandals M2',' Footwear',6652438,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Speaker N2',' Electronics',6080392,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' T-Shirt O2',' Clothing',1156398,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Hat P2',' Accessories',3765790,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Running Shoes Q2',' Footwear',925348,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Backpack R2',' Accessories',6394052,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Camera S2',' Electronics',2765209,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Shorts T2',' Clothing',4815955,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Lipstick U2',' Beauty',4566235,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Sunglasses V2',' Accessories',1625845,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (9,' Guitar W2',' Music',6833592,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Shirt X2',' Clothing',4706596,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Moisturizer Y2',' Beauty',454126,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Necklace Z2',' Accessories',2294662,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Umbrella A3',' Accessories',1678905,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Jacket B3',' Clothing',1531093,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Wallet C3',' Accessories',6705540,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Sneakers D3',' Footwear',927742,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Backpack E3',' Accessories',6524865,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Tablet F3',' Electronics',4454448,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Watch G3',' Accessories',499041,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Headphones H3',' Electronics',5965321,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Jeans I3',' Clothing',4904936,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Bracelet J3',' Accessories',3405483,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' Skirt K3',' Clothing',3060819,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (7,' Cologne L3',' Beauty',2639982,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Sandals M3',' Footwear',5364510,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Speaker N3',' Electronics',6766469,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (1,' T-Shirt O3',' Clothing',5032429,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Hat P3',' Accessories',823473,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (4,' Running Shoes Q3',' Footwear',1326953,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (2,' Backpack R3',' Accessories',1176704,500);
INSERT INTO `` (`produk_id`,`product_name`,`category`,`price`,`inventory`) VALUES (6,' Camera S3',' Electronics',776955,500);
